name: Build and Push to ECR

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
  workflow_dispatch:

env:
  AWS_REGION: eu-north-1
  ECR_REPOSITORY: url-shortener

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::501235162976:role/github-actions-ecs-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build with version tag
          VERSION="v$(date +%Y%m%d-%H%M%S)"
          docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION ./app
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          # Push all tags
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$VERSION
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          
          echo "📦 Pushed tags: $VERSION, $IMAGE_TAG, latest"
          echo "IMAGE=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Deploy to ECS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecs update-service \
            --cluster url-shortener-cluster-dev \
            --service url-shortener-service-dev \
            --force-new-deployment \
            --region ${{ env.AWS_REGION }}
          
          echo "✅ Deployment triggered successfully!"
          echo "🚀 ECS is rolling out new version with zero downtime"
